#!/bin/sh
[ -f /etc/dnsmasq.conf ] || exit 0

LAN_IP=$(sed -n 's/^LAN_IP=//p' /data/rns/config.env 2>/dev/null | head -n1)
[ -n "$LAN_IP" ] || LAN_IP=192.168.50.1
NET=$(echo "$LAN_IP" | cut -d. -f1-3)

sed -i "s|^dhcp-range=.*|dhcp-range=${NET}.50,${NET}.200,12h|" /etc/dnsmasq.conf
sed -i "s|^dhcp-option=option:router.*|dhcp-option=option:router,${LAN_IP}|" /etc/dnsmasq.conf
sed -i "s|^dhcp-option=option:dns-server.*|dhcp-option=option:dns-server,${LAN_IP}|" /etc/dnsmasq.conf

/usr/sbin/dnsmasq --conf-file=/etc/dnsmasq.conf --pid-file=/var/run/dnsmasq.pid
echo "[dnsmasq] started on br0"
exit 0
