interface=br0
bind-interfaces
dhcp-range=192.168.50.50,192.168.50.200,12h
dhcp-option=option:router,192.168.50.1
dhcp-option=option:dns-server,192.168.50.1
no-resolv
server=1.1.1.1
server=8.8.8.8
cache-size=500
log-queries=no
